language: go
go_import_path: github.com/google/mtail
before_install:
  - go get github.com/laher/goxc
go:
- 1.6
script: make && go test
sudo: false
deploy:
  provider: releases
  api_key:
    secure: M3nVdfPEQOrfwH1HEQpm818Z6oKNsVS0k7J153OCNdgFBbJqTJVIEFeGajrSqjANY4hCkfjNoMMrdqLIQslKBudf5wLirDwKShXdhgcrXEafex+vEmfGiDA3dRXvSCEoKW3czPFCIu1p6HBR28Jsql/CprBsUlQHVmbeims3qgcUm+FiGciDWJDpVgftLh4hPTvzvUD+2Jx1vaZmpyvsPRt50znm8k/nzdkd43ZG3MVazyNk2blJb4hCzPfsaqLdFCrlNJ24a99x4KP/sl6mEXzj3WUq/MCyWrsn2sUx1LdYNEkZAlfDPZ0FEkJMloGbXJ6ydAtmTj8i6UlYBecF5DeUEq60SzkgHrgDSE/fydVB2QM+ChQKE3BfSomSJj5/kRQWxj1uA/CfT3FksPqwU4x3fLZUs/BKbpgQbDMNJrfWlZog8tzCrNYa+/pUYUWEyKeiGB56VF3BiAt3x2yeRBad/g+pWUUUjqD/0hd7ySJN4ZRWwdCjE2Kibqe3coiPcAoRrRSrBxgxyFkf8/S1PcRm2yCjWlC2OoSRH4WOhzJmSMv4xielajJqts5iPK+1duDNju6TwQKx0fyL0ijtQX53ySlY2oyS3penNNbxfvKl86WTtbPcS3iZUUQWnBPPZSRDQad637LF/65C+PGVhsbRS6SADunb5c0k4bS3Jyo=

  skip_cleanup: true
  file_glob: true
  file: 
    - bin/$TRAVIS_TAG/*.zip
    - bin/$TRAVIS_TAG/*.gz
    - bin/$TRAVIS_TAG/*.deb
  on:
    tags: true
    repo: jarro2783/mtail
