language: go

go_import_path: github.com/google/mtail

# Run tests at these Go versions.
go:
  - tip
  - 1.6
  - 1.5
  - 1.4
  
script: make && go test

# GOMAXPROCS=1 forces scheduling race bugs.
env:
  - GOMAXPROCS=1
  - GOMAXPROCS=2
  - GOMAXPROCS=4

# Allow tip to fail, and only wait for mature versions to succeed before
# reporting build status.
matrix:
  fast_finish: true
  allow_failures:
    - go: tip
    - go: 1.6


# Not using sudo, can use containers.
sudo: false
