language: go
go_import_path: github.com/google/mtail
before_install:
  - go get github.com/laher/goxc
  - go get github.com/go-test/deep
go:
  - tip
script: make && go test
sudo: false
deploy:
  provider: releases
  api_key:
    secure: Pr7lg6MmOkWG2MEXgfhV7mIgHloPZ2X/DiUxQ7w3GAYjhna0zGEFS0tMxhQ8znJYnBz9J8nu+3ZgFZhWF+vYKX1gvfnYEfcrDtU5gNFKTRdB3DOoSMLwqdD6KNeP1q/wQCIAZPci9mPnL8SvMjeYeb6/LZyNtq8dlpItrFZpdGxHLNSztMAuHG34rEmI21U/BlPPkULNocLgrK2HADHGgAmQgfeEdZYsuXV+ny6ydw5YaZck7JJZNETuVanR4VfoK8sdzgXOAZOOE03oiyiQaqv+q7SPTIgtT+BonBJhgbyI0sFuG7tDvf0vp4gOeq68ZokFOGWYLWaBAvogN7S/U7M2lxbvYIFxCQjBUuYVo1RYnZr6d7H0dfZsGRbEbaooitURnsR586IRCjtW68tHJS+uQlzAn5NEh3dVzEHQX1tZVmZmVQyJhIWRDHYudGI0qYNG3SYClVHbHc9oKlwLzrZJDbPlvaDJjilFh/jzXmWaducjNOo1zHtbMB5GrHh5UDXvnUg2A62oIATFygDHhq4u+M7NVciugiO9q3O83i+qxxwF4/WN0r4jshVP2GALxievs9WA9EIgO8LJueN3ua7OYubdsXpfvHTflmX6i2ujaxMum4HMioya7Ph3qTTupD8HXEWAO3cLuG3mxoKtLDAMCl7F4nVeETaKcSYbcOs=
  skip_cleanup: true
  file_glob: true
  file: 
    - bin/$TRAVIS_TAG/*.zip
    - bin/$TRAVIS_TAG/*.gz
    - bin/$TRAVIS_TAG/*.deb
  on:
    tags: true
    repo: jarro2783/mtail
